// Client for the Pagefind index generated by `npm run build`.
// Each [data-search] root gets live results, a status region and arrow-key movement.

interface PagefindData {
  url: string;
  excerpt: string;
  meta: Record<string, string | undefined>;
}

interface Pagefind {
  options(options: Record<string, unknown>): Promise<void>;
  init(): Promise<void>;
  search(query: string): Promise<{ results: { data(): Promise<PagefindData> }[] }>;
}

const MAX_RESULTS = 8;
const DEBOUNCE_MS = 150;

let pagefind: Promise<Pagefind> | undefined;

function loadPagefind(): Promise<Pagefind> {
  if (!pagefind) {
    const path = '/pagefind/pagefind.js';
    pagefind = import(/* @vite-ignore */ path).then(async (pf: Pagefind) => {
      await pf.options({ excerptLength: 24 });
      await pf.init();
      return pf;
    });
    // Allow a retry after a failed load.
    pagefind.catch(() => (pagefind = undefined));
  }
  return pagefind;
}

function summary(total: number, query: string): string {
  if (total === 0) return `Sin resultados para «${query}». Prueba con otra palabra o explora los temas.`;
  const found = total === 1 ? `1 resultado para «${query}».` : `${total} resultados para «${query}».`;
  return total > MAX_RESULTS ? `${found} Se muestran los ${MAX_RESULTS} más relevantes.` : found;
}

function renderResult(data: PagefindData): HTMLLIElement {
  const item = document.createElement('li');
  item.className = 'result';

  const title = document.createElement('a');
  title.className = 'result-title';
  title.href = data.url;
  title.textContent = data.meta.title ?? data.url;

  const meta = document.createElement('p');
  meta.className = 'meta';
  meta.textContent = [data.meta.tema, data.meta.fecha].filter(Boolean).join(' · ');

  // Pagefind escapes the page text and only adds <mark> around matches.
  const excerpt = document.createElement('p');
  excerpt.className = 'result-excerpt';
  excerpt.innerHTML = data.excerpt;

  item.append(title, meta, excerpt);
  return item;
}

function setup(root: HTMLElement) {
  const form = root.querySelector('form')!;
  const input = root.querySelector<HTMLInputElement>('input[type="search"]')!;
  const status = root.querySelector<HTMLElement>('[role="status"]')!;
  const list = root.querySelector<HTMLOListElement>('.search-results')!;
  const syncUrl = root.hasAttribute('data-search-sync-url');

  let attempt = 0;
  let timer: ReturnType<typeof setTimeout> | undefined;

  function announce(message: string) {
    // Empty first so a repeated message is announced again.
    status.textContent = '';
    requestAnimationFrame(() => (status.textContent = message));
  }

  async function run() {
    clearTimeout(timer);
    const query = input.value.trim();
    const mine = ++attempt;

    if (syncUrl) {
      const url = new URL(location.href);
      if (query) url.searchParams.set('q', query);
      else url.searchParams.delete('q');
      history.replaceState(null, '', url);
    }

    if (!query) {
      list.replaceChildren();
      status.textContent = '';
      return;
    }

    try {
      const pf = await loadPagefind();
      const { results } = await pf.search(query);
      const data = await Promise.all(results.slice(0, MAX_RESULTS).map((result) => result.data()));
      if (mine !== attempt) return;
      list.replaceChildren(...data.map(renderResult));
      announce(summary(results.length, query));
    } catch {
      if (mine !== attempt) return;
      list.replaceChildren();
      announce(
        import.meta.env.DEV
          ? 'No hay índice de búsqueda. Ejecuta npm run build y vuelve a probar.'
          : 'La búsqueda no está disponible ahora mismo. Inténtalo de nuevo en un momento.',
      );
    }
  }

  input.addEventListener('focus', () => loadPagefind().catch(() => {}), { once: true });
  input.addEventListener('input', () => {
    clearTimeout(timer);
    timer = setTimeout(run, DEBOUNCE_MS);
  });
  form.addEventListener('submit', (event) => {
    event.preventDefault();
    run();
  });

  // Arrow keys move between the field and the result links; Tab still works.
  root.addEventListener('keydown', (event) => {
    if (event.key !== 'ArrowDown' && event.key !== 'ArrowUp') return;
    const links = [...list.querySelectorAll<HTMLAnchorElement>('.result-title')];
    if (links.length === 0) return;
    const stops: HTMLElement[] = [input, ...links];
    const index = stops.indexOf(document.activeElement as HTMLElement);
    if (index === -1) return;
    const next = event.key === 'ArrowDown' ? Math.min(index + 1, stops.length - 1) : Math.max(index - 1, 0);
    event.preventDefault();
    stops[next].focus();
  });

  if (syncUrl) {
    const query = new URLSearchParams(location.search).get('q');
    if (query) {
      input.value = query;
      run();
    }
  }
}

for (const root of document.querySelectorAll<HTMLElement>('[data-search]')) setup(root);
